[package]
name = "ParseTable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.9.0"
serde = "1.0.149"
serde_json = "1.0.89"

